### ISSUE TITLE
Error swapping

### ISSUE THREAD

**Issue by djmbritt** [effectai/effect-js#112]
There is an error swapping on eos mainnet, I've notifed it while bootstrapping the testing framework.

✓ Swap > swap() should throw an error when Session is not set on Client. [0.29ms]

93 |                    efxPrice,
94 |            });
95 | 
96 |            return await transact({ action });
97 |    } catch (e) {
98 |            throw new Error(`Error swapping tokens\n${e}`);
             ^
error: Error swapping tokens
Error: transaction declares authority 
'{"actor":"cryptonode42","permission":"owner"}', but does not have signatures for it under a provided delay of 0 ms, 
provided permissions [], 
provided keys ["redacted_key_here"], 
and a delay max limit of 3888000000 ms
at /home/djmbritt/Effect/effect-js/src/actions/token/swap.ts:98:9

I'm not understanding what the error is, but I'm writing it here for future reference.
First thoughts are as stated in the error message, that the transasction is not signed by the owner, but I'm pretty sure I'm using the right keys, need to double check that.

**Comment by djmbritt** [comment]
Great, let me check it.

**Comment by djmbritt** [comment]
Nope, that's not it, still getting the same error.

```
error: transaction declares authority '{"actor":"cryptonode42","permission":"owner"}', but does not have signatures for it under a provid
ed delay of 0 ms, provided permissions [], provided keys ["redacted_key"], and a delay max limit
 of 3888000000 ms
 ```
 I'm thinking it has to be a parameter somewhere in the Session.

**Comment by Jeffrieh** [comment]
these errors seem to be related to undeployed contracts on mainnet
