### ISSUE TITLE
Switch to @wharfkit/antelope

### ISSUE THREAD

**Issue by jeisses** [effectai/effect-js#91]
The SDK is currently based on the deprecated `eosjs` package. Wharfkit (greymass) has a new maintained Typescript package that looks like a better lightweight option

**Comment by jeisses** [comment]
Good catch, so there are 2 well maintained javascript packages. 
I've been experimenting with wharfkit/antelope in React Native and it has been easy to use so far.
We should check what is the preferred one, I'll ask around

**Comment by djmbritt** [comment]
The ENF package is almost identical to the eosjs package.
I think it will be easier and faster to migrate to the ENF/eosjs package.

But I'm sure the wharfkit package has learned from the mistakes of the original eosjs.

**Comment by jeisses** [comment]
The `sdk-v2` has switched to @wharfkit/antelope now and it works great
